package com.ecomerce.demo.repositories;

import com.ecomerce.demo.model.Comment;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 22/06/2018
*/
@Repository
public interface CommentRepository extends JpaRepository<Comment, Integer>{

	
}
