package com.ecomerce.demo.repositories;

import com.ecomerce.demo.model.Orders;
import com.ecomerce.demo.model.Product;

import java.util.List;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 22/06/2018
*/
@Repository
public interface OrdersRepository extends JpaRepository<Orders, Integer>, JpaSpecificationExecutor<Orders> {
	
	@Query("SELECT o from Orders o")
	public List<Orders> findOrders();

	@Query("SELECT o.product FROM Orders o WHERE o.perdoruesi.id =:userId")
	public List<Product> findSoldProducts(@Param("userId") int userId);
	
	@Query("SELECT o.product FROM Orders o WHERE o.perdoruesi.id =:userId")
	Page<Product> findProductsSold(@Param("userId") int userId, Pageable pageable);

}
